[package]
name = "ha-localizer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
reqwest = { version = "0.13", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }

[profile.release]
strip = true
lto = true
